/* eslint-disable import/no-unresolved, import/no-extraneous-dependencies */
/*
	Husky config file: https://github.com/typicode/husky
	Configures git hooks
	Generated by rel-engage
*/

'use strict';

module.exports = require('@financial-times/rel-engage/packages/dotfiles/husky');
