version: 2.1

orbs:
  ft-snyk-orb: financial-times/ft-snyk-orb@0

references:
  container_config: &container_config
    working_directory: ~/project/lambda-logger
    docker:
      - image: cimg/node:14.18.3

  workspace_root: &workspace_root ~/project

  persist_workspace: &persist_workspace
    persist_to_workspace:
      root: ~/project
      paths:
        - lambda-logger

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  npm_cache_key: &npm_cache_key v5-dependency-npm-{{ checksum "package-lock.json" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules

  only_version_tags: &only_version_tags
    tags:
      only: /^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta)\.\d+)?$/

jobs:
  install:
    <<: *container_config
    steps:
      - checkout
      - *restore_node_modules

      - run:
          name: Install dependencies
          command: npm install

      - *cache_node_modules
      - *persist_workspace

  build:
    <<: *container_config
    steps:
      - *attach_workspace

      - run:
          name: Run build
          command: make build

      - *persist_workspace

  test:
    <<: *container_config
    steps:
      - *attach_workspace

      - run:
          name: Run verification
          command: make verify -j 4

      - run:
          name: Run tests
          command: npm test

  release:
    <<: *container_config
    steps:
      - *attach_workspace

      - deploy:
          name: npm publish
          description: 'Overwrite the default npm registry URL with the access token appended to it. Once authenticated, publish the lambda-logger to the npm registry'
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
            make npm-publish

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test:
          context: rel-eng-creds
          requires:
            - install
            - build
          filters:
            tags:
              only: /.*/
      #Scan package.json for vulnerable dependencies while developing
      - ft-snyk-orb/scan-js-packages:
          context: rel-eng-creds
          requires:
            - install
          filters: *only_version_tags
      - release:
          context: npm-publish-token
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      #Scan and monitor vulnerabilities once in production
      - ft-snyk-orb/scan-and-monitor-js-packages:
          name: snyk-scan-and-monitor
          context: rel-eng-creds
          requires:
            - release
          filters:
            <<: *only_version_tags
            branches:
              ignore: /.*/

experimental:
  notify:
    branches:
      only:
        - main
