version: 2

references:

  container_config_argon: &container_config_argon
    working_directory: ~/project/lambda-logger
    docker:
      - image: circleci/node:4.3.2

  container_config_boron: &container_config_boron
    working_directory: ~/project/lambda-logger
    docker:
      - image: circleci/node:6.10.3

  container_config_carbon: &container_config_carbon
    working_directory: ~/project/lambda-logger
    docker:
      - image: circleci/node:carbon

  workspace_root: &workspace_root
    ~/project

  persist_workspace: &persist_workspace
    persist_to_workspace:
      root: ~/project
      paths:
        - lambda-logger

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  npm_cache_key: &npm_cache_key
    v1-dependency-npm-{{ checksum "package-lock.json" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules

jobs:
  install:
    <<: *container_config_carbon
    steps:
      - checkout
      - *restore_node_modules

      - run:
          name: Install dependencies
          command: npm install

      - *cache_node_modules
      - *persist_workspace

  test:argon:
    <<: *container_config_argon
    steps:
      - *attach_workspace

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Run build
          command: npm run build

  test:boron:
    <<: *container_config_boron
    steps:
      - *attach_workspace

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Run tests
          command: npm run coverage && npm run coverage:submit

      - run:
          name: Run build
          command: npm run build

      - *persist_workspace

  test:carbon:
    <<: *container_config_carbon
    steps:

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Run build
          command: npm run build

  release:
    <<: *container_config_carbon
    steps:
      - *attach_workspace

      - deploy:
          command: |
            sudo npm install -g npm-cli-login
            NPM_USER=$NPM_USER NPM_PASS=$NPM_PASSWORD NPM_EMAIL=$NPM_EMAIL npm-cli-login
            npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test_argon:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test_boron:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test_carbon:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test_argon
            - test_boron
            - test_carbon
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

experimental:
  notify:
    branches:
      only:
        - master
